sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "PTG+z74j/g9j/jHSvloVrb60deS+p7hG8bX2Ybnbrj2FMxyUlMABrWZTwc+P4xHAwgvSW3RmUvb6jgIxAnXLcGFnZn4okV37vaQuNnBGprJbXOCYL2AVtxnujpsIZ4CZkYYXu2c/6FqjMfZ8z6pUjv1pYHF0XttlUL8Oqt044Ck3GOQi20fzPAS2zQoyfk8VFyYMvYkf9uvdGubeA/fyAeBv96GYsKOqXHSvYMKu2Uq1LPWjT049K1Jhg7e8UhxDJkWLR0mNvltP7Ns3SbxMx/Di8rQVWpmXPO+EVRdMobHBMqjEBwrIdmI3lop0yIBHTqlBmWPxJaIQtfbL8qmL0dn8hp3Bi442W/GMgTYDozptj+7trR+wF/l3eJcBSw8FirO/QqThPBrK22gkEomoyVOcV+gNOjhp2EssDaAXa1q/QCrzvmpQ6BoDdALCKw+bRFOMM0Mr1MeB8wqGyO358HLFC294riAVPJEzYKIIGiyuvkNp+YRTPiiUy8hgnSy33QPIfVia/XpS89CHVpVd+fbMp74FBNVuRiiy899XVlARI/uYMmybuUENcA1TCp4bRitf6yNQpFG5TQ/SLxBpBjGEKqs4Yb+ODJ1jVTcO6gCPZENcujsdaHuZetDN18YyzHZOyEwZnJYnzpgpmSpc8OpkOY8VUcjm7Sxv/Se20jk="
  - secure: "Le+eIF9zToyHYs+ZcGowg0yuJWzdpkTjnTFpWQw85hE3VSJhWCCVzC5Z1iBMlJV7imla0wCsPaCTfuIDszmNbBSOA5FNWdu6ZSj2f77ob1R9rmjI1tGBSEODu4bHQO7MrDSOXm5Rk+8FTc4L9wxvXZ7wND8noJcVg8IhCvoCrYZqjp3iEuYy9m1GDFP7tmd99kZzngY2an7eI0DN/DhtmLVWVACPfLAyXgajPyRrDrNxFydLAlbYck/2Nfz+SrOfR6IUDqGAlf5KPhJL4e4ttsoCZoGLft4XCA19tPHLFS+8v1b+QT5x/Uin20/8D+VVxofpwY7XycB51qiY+L4fA8KY3NULzQuaLIt3YO4rnzOyALg+9gdGgYKSsPMonpRkI+XhFdaJ5/moQZytgBi7NRDb9CX1HkKOICGw4TFrMJtg+3qoXcyIJ8WaiC57JMS808yVwzIDWzbJ84iTQzXciw9ljSjFsYTduZDURedwwEDn3sZzQJIGO0OxRc1ACnyqA/1a957ByaJtHcdvt2obtktecTzLFhAxP9fXrNAJjN0oIjQdV8NDidU1DmR8lXJFxsLfLaJcX//UR5r7B6Hkm9XO0Lpg7Y2r2dPsslt3W181LtgPIzDbXMgqjdCk0ykXMGb1KGKH4TCX2/ZO4D+2i6y/1hEh4r6abmi4Zu5Cn8c="
  - secure: "QDPu/3G7dK6PFt01UDcsGpcx4LKKVi0x+BQMgXSipUCqib5sUwc0WTlva04bjyPJZrns74+S5uUTJ4PeJISG5xciyD4JVWMXp8ZeIdGA7DHdLzwjItaSXfbQlOvrWmyypceblRtzCEWM3INVbflIN3u/UiT+75j9IeB7YuISc9xa/vSKoe5s7dyGiWjlGeRhPsqnR5g4bRTsKr8/9X0m3usYSYXvN7xfwWIaENQtb3VpHySg9apqPd1LAf3EwBQuWS8IWdRLGukYmCqM9pw/cHxUaHlGmExF58DpGAAyXY1BPaWd/OcY96znhP+TgqLTn7WE03x7FgmvdlZVKHdyPFzzxk6b7+KXtYAdD98mL9+GJUMxTk3hJ9306vXOLn26OzOIlyQctknWzMD7tz3H1IY6Jfx9PTIOZhHygq7Q2fxSx8lNI3RDJZL5aNNEcIzHzMqc9ZRBdrot0YZ4eCSpbSPTlP/fmsepl4FVggXENCYJjI6xwDre+OA1m9JBlM3E+vvxLxvyjnItTPqSVxtXEgSbmymGezoZnjWDBHesp/nZTo3zxE8SesyoStTiiLebSsZpKw+uYBqXQBc529EggegmXLmAUIsfd14atLT9QC3TjWZrxnV33Cyc63D6pB96otcS/JWcoWL8XWVFvW5jyEhAEmaxSNrvci2QvfB/Yn0="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
