sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "BKKRiWrqeBGw0/tyJgRMyskgmSZyxYpTA7taDvvb9bHbeCGk7APHM8SubXQxHDTN7iSs8MHhu96D1QrOKUYTj6hFGR9LKfW6e9asb/ohCTy8VdCinjIiM7tP4bgIQf1G4VtwzMJ/RawQy2Nzw3DdFBAveGNXxncqWgpIfqA/MVpznaUZyyHVLx0hhJZK4uoo7Y51b4ovJ5eAtl7bdbpoVlxuTmz8bhx6TFgo2bMZPwlXjDFqkkWfZVe5uOa8iAgkQs7JUxDORopZ8JwPPsmxIsenLcsB2UjlLNrFXXTEUfNEE4UBVgV1o9N3elNKfphZyHBiAQ90lf6sq/yFpIlnDIReWM8U3nl6KcX6UE2iCOXcN8aB6Cf4oL8pnoPypAZc6lgjYwClJ7rjZvovDZJ8m+ySdH135x7IWHcZIGDFzPoffNE7pq0lnNy2mkL76Oj9iXWqZf+He6ZogRQ3o84QmkwLfccmvnoyMDCp6K3ck8oi7pPtxlW/v/aNmyAi/OE9uH4yseAaF45eqZMIrmFCyF+/VFBY0zQ+dBWsONWuLN7lpXGIuMXd24taajP9iqYQ9z1VQH03MPnAQj7d2NRPZ9kNlM9ebQOrNKhRQ5qbSFKZyH4cY3lS7YtvWNbty+XDlbp1RhGSNhogqYhxHJDH289GoMFBuSRO0/Bu8oLOarw="
  - secure: "Le+eIF9zToyHYs+ZcGowg0yuJWzdpkTjnTFpWQw85hE3VSJhWCCVzC5Z1iBMlJV7imla0wCsPaCTfuIDszmNbBSOA5FNWdu6ZSj2f77ob1R9rmjI1tGBSEODu4bHQO7MrDSOXm5Rk+8FTc4L9wxvXZ7wND8noJcVg8IhCvoCrYZqjp3iEuYy9m1GDFP7tmd99kZzngY2an7eI0DN/DhtmLVWVACPfLAyXgajPyRrDrNxFydLAlbYck/2Nfz+SrOfR6IUDqGAlf5KPhJL4e4ttsoCZoGLft4XCA19tPHLFS+8v1b+QT5x/Uin20/8D+VVxofpwY7XycB51qiY+L4fA8KY3NULzQuaLIt3YO4rnzOyALg+9gdGgYKSsPMonpRkI+XhFdaJ5/moQZytgBi7NRDb9CX1HkKOICGw4TFrMJtg+3qoXcyIJ8WaiC57JMS808yVwzIDWzbJ84iTQzXciw9ljSjFsYTduZDURedwwEDn3sZzQJIGO0OxRc1ACnyqA/1a957ByaJtHcdvt2obtktecTzLFhAxP9fXrNAJjN0oIjQdV8NDidU1DmR8lXJFxsLfLaJcX//UR5r7B6Hkm9XO0Lpg7Y2r2dPsslt3W181LtgPIzDbXMgqjdCk0ykXMGb1KGKH4TCX2/ZO4D+2i6y/1hEh4r6abmi4Zu5Cn8c="
  - secure: "QDPu/3G7dK6PFt01UDcsGpcx4LKKVi0x+BQMgXSipUCqib5sUwc0WTlva04bjyPJZrns74+S5uUTJ4PeJISG5xciyD4JVWMXp8ZeIdGA7DHdLzwjItaSXfbQlOvrWmyypceblRtzCEWM3INVbflIN3u/UiT+75j9IeB7YuISc9xa/vSKoe5s7dyGiWjlGeRhPsqnR5g4bRTsKr8/9X0m3usYSYXvN7xfwWIaENQtb3VpHySg9apqPd1LAf3EwBQuWS8IWdRLGukYmCqM9pw/cHxUaHlGmExF58DpGAAyXY1BPaWd/OcY96znhP+TgqLTn7WE03x7FgmvdlZVKHdyPFzzxk6b7+KXtYAdD98mL9+GJUMxTk3hJ9306vXOLn26OzOIlyQctknWzMD7tz3H1IY6Jfx9PTIOZhHygq7Q2fxSx8lNI3RDJZL5aNNEcIzHzMqc9ZRBdrot0YZ4eCSpbSPTlP/fmsepl4FVggXENCYJjI6xwDre+OA1m9JBlM3E+vvxLxvyjnItTPqSVxtXEgSbmymGezoZnjWDBHesp/nZTo3zxE8SesyoStTiiLebSsZpKw+uYBqXQBc529EggegmXLmAUIsfd14atLT9QC3TjWZrxnV33Cyc63D6pB96otcS/JWcoWL8XWVFvW5jyEhAEmaxSNrvci2QvfB/Yn0="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
